# Generated by Django 5.1.15 on 2026-03-20 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisationen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="core.organization",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einrichtung",
                "verbose_name_plural": "Einrichtungen",
                "ordering": ["name"],
            },
        ),
    ]
