# Generated by Django 5.1.15 on 2026-03-20 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_organization_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Anzeigename"),
        ),
        migrations.AddField(
            model_name="user",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.facility",
                verbose_name="Einrichtung",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notizen"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
        ),
    ]
