# Generated by Django 5.1.15 on 2026-03-20 02:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_extend"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pseudonym", models.CharField(db_index=True, max_length=100, verbose_name="Pseudonym")),
                (
                    "contact_stage",
                    models.CharField(
                        choices=[("identified", "Identifiziert"), ("qualified", "Qualifiziert")],
                        default="identified",
                        max_length=20,
                        verbose_name="Kontaktstufe",
                    ),
                ),
                (
                    "age_cluster",
                    models.CharField(
                        choices=[("u18", "Unter 18"), ("18_26", "18–26"), ("27_plus", "27+"), ("unknown", "Unbekannt")],
                        default="unknown",
                        max_length=20,
                        verbose_name="Altersgruppe",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notizen")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_clients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="core.facility",
                        verbose_name="Einrichtung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Klient",
                "verbose_name_plural": "Klienten",
                "ordering": ["pseudonym"],
                "constraints": [
                    models.UniqueConstraint(fields=("facility", "pseudonym"), name="unique_facility_pseudonym")
                ],
            },
        ),
    ]
