# Generated by Django 5.1.15 on 2026-03-20 02:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("contact", "Kontakt"),
                            ("service", "Leistung"),
                            ("admin", "Verwaltung"),
                            ("note", "Notiz"),
                        ],
                        default="contact",
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[("normal", "Normal"), ("elevated", "Erhöht"), ("high", "Hoch")],
                        default="normal",
                        max_length=20,
                        verbose_name="Sensibilität",
                    ),
                ),
                (
                    "min_contact_stage",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="Mindest-Kontaktstufe"),
                ),
                (
                    "retention_days",
                    models.IntegerField(blank=True, null=True, verbose_name="Aufbewahrungsfrist (Tage)"),
                ),
                ("icon", models.CharField(blank=True, max_length=50, verbose_name="Icon")),
                ("color", models.CharField(blank=True, max_length=20, verbose_name="Farbe")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_types",
                        to="core.facility",
                        verbose_name="Einrichtung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumentationstyp",
                "verbose_name_plural": "Dokumentationstypen",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FieldTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Textbereich"),
                            ("number", "Zahl"),
                            ("date", "Datum"),
                            ("time", "Uhrzeit"),
                            ("boolean", "Ja/Nein"),
                            ("select", "Auswahl"),
                            ("multi_select", "Mehrfachauswahl"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Feldtyp",
                    ),
                ),
                ("is_required", models.BooleanField(default=False, verbose_name="Pflichtfeld")),
                ("is_encrypted", models.BooleanField(default=False, verbose_name="Verschlüsselt")),
                ("options_json", models.JSONField(blank=True, default=list, verbose_name="Optionen (JSON)")),
                (
                    "statistics_category",
                    models.CharField(blank=True, max_length=100, verbose_name="Statistik-Kategorie"),
                ),
                ("help_text", models.CharField(blank=True, max_length=200, verbose_name="Hilfetext")),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_templates",
                        to="core.facility",
                        verbose_name="Einrichtung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feldvorlage",
                "verbose_name_plural": "Feldvorlagen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTypeField",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="core.documenttype",
                        verbose_name="Dokumentationstyp",
                    ),
                ),
                (
                    "field_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_type_fields",
                        to="core.fieldtemplate",
                        verbose_name="Feldvorlage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumentationstyp-Feld",
                "verbose_name_plural": "Dokumentationstyp-Felder",
                "ordering": ["sort_order"],
                "constraints": [
                    models.UniqueConstraint(fields=("document_type", "field_template"), name="unique_doctype_field")
                ],
            },
        ),
    ]
