# Generated by Django 5.1.15 on 2026-03-20 02:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_documenttype_fieldtemplate_documenttypefield"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("occurred_at", models.DateTimeField(verbose_name="Zeitpunkt")),
                ("data_json", models.JSONField(default=dict, verbose_name="Daten (JSON)")),
                ("is_anonymous", models.BooleanField(default=False, verbose_name="Anonym")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Gelöscht")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="core.client",
                        verbose_name="Klient",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="core.documenttype",
                        verbose_name="Dokumentationstyp",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.facility",
                        verbose_name="Einrichtung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ereignis",
                "verbose_name_plural": "Ereignisse",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="EventHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("changed_at", models.DateTimeField(auto_now_add=True, verbose_name="Geändert am")),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Erstellt"), ("update", "Aktualisiert"), ("delete", "Gelöscht")],
                        max_length=10,
                        verbose_name="Aktion",
                    ),
                ),
                ("data_before", models.JSONField(blank=True, null=True, verbose_name="Daten vorher")),
                ("data_after", models.JSONField(blank=True, null=True, verbose_name="Daten nachher")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="core.event",
                        verbose_name="Ereignis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ereignis-Historie",
                "verbose_name_plural": "Ereignis-Historien",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["client", "-occurred_at"], name="core_event_client__234d9b_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["document_type", "-occurred_at"], name="core_event_documen_3d146b_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["facility", "-occurred_at"], name="core_event_facilit_e146b4_idx"),
        ),
    ]
