# Generated by Django 5.1.15 on 2026-03-20 02:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_event_eventhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeFilter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=100, verbose_name="Bezeichnung")),
                ("start_time", models.TimeField(verbose_name="Startzeit")),
                ("end_time", models.TimeField(verbose_name="Endzeit")),
                ("is_default", models.BooleanField(default=False, verbose_name="Standard")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sortierung")),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_filters",
                        to="core.facility",
                        verbose_name="Einrichtung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zeitfilter",
                "verbose_name_plural": "Zeitfilter",
                "ordering": ["sort_order", "start_time"],
            },
        ),
    ]
