# Generated by Django 5.1.15 on 2026-03-20 02:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_timefilter"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletionRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_type", models.CharField(max_length=100, verbose_name="Zieltyp")),
                ("target_id", models.UUIDField(verbose_name="Ziel-ID")),
                ("reason", models.TextField(verbose_name="Begründung")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ausstehend"), ("approved", "Genehmigt"), ("rejected", "Abgelehnt")],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Geprüft am")),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_requests",
                        to="core.facility",
                        verbose_name="Einrichtung",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Beantragt von",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geprüft von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Löschantrag",
                "verbose_name_plural": "Löschanträge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("hint", "Hinweis"), ("task", "Aufgabe")],
                        default="task",
                        max_length=10,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("in_progress", "In Bearbeitung"),
                            ("done", "Erledigt"),
                            ("dismissed", "Verworfen"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("important", "Wichtig"), ("urgent", "Dringend")],
                        default="normal",
                        max_length=20,
                        verbose_name="Priorität",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_work_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Zugewiesen an",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_items",
                        to="core.client",
                        verbose_name="Klient",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_work_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_items",
                        to="core.facility",
                        verbose_name="Einrichtung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arbeitsauftrag",
                "verbose_name_plural": "Arbeitsaufträge",
                "ordering": ["-created_at"],
            },
        ),
    ]
