# Generated by Django 5.1.15 on 2026-03-20 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_workitem_deletionrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Anmeldung"),
                            ("logout", "Abmeldung"),
                            ("login_failed", "Anmeldung fehlgeschlagen"),
                            ("view_qualified", "Qualifizierte Daten eingesehen"),
                            ("export", "Export"),
                            ("delete", "Löschung"),
                            ("stage_change", "Stufenwechsel"),
                            ("settings_change", "Einstellungen geändert"),
                        ],
                        max_length=30,
                        verbose_name="Aktion",
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=100, verbose_name="Zieltyp")),
                ("target_id", models.CharField(blank=True, max_length=100, verbose_name="Ziel-ID")),
                ("detail", models.TextField(blank=True, verbose_name="Details")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP-Adresse")),
                ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Zeitstempel")),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.facility",
                        verbose_name="Einrichtung",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit-Log",
                "verbose_name_plural": "Audit-Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Offen"), ("closed", "Geschlossen")],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("closed_at", models.DateTimeField(blank=True, null=True, verbose_name="Geschlossen am")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="core.client",
                        verbose_name="Klient",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="core.facility",
                        verbose_name="Einrichtung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fall",
                "verbose_name_plural": "Fälle",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="core.case",
                verbose_name="Fall",
            ),
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "facility",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to="core.facility",
                        verbose_name="Einrichtung",
                    ),
                ),
                ("facility_full_name", models.CharField(blank=True, max_length=300, verbose_name="Vollständiger Name")),
                ("session_timeout_minutes", models.IntegerField(default=30, verbose_name="Session-Timeout (Minuten)")),
                (
                    "retention_anonymous_days",
                    models.IntegerField(default=90, verbose_name="Aufbewahrung anonym (Tage)"),
                ),
                (
                    "retention_identified_days",
                    models.IntegerField(default=365, verbose_name="Aufbewahrung identifiziert (Tage)"),
                ),
                (
                    "retention_qualified_days",
                    models.IntegerField(default=3650, verbose_name="Aufbewahrung qualifiziert (Tage)"),
                ),
                (
                    "default_document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.documenttype",
                        verbose_name="Standard-Dokumentationstyp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einstellungen",
                "verbose_name_plural": "Einstellungen",
            },
        ),
    ]
