# Generated by Django 5.1.15 on 2026-03-20 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_case_auditlog_settings_event_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitem',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Arbeitsauftrag', 'verbose_name_plural': 'Arbeitsaufträge'},
        ),
        migrations.AddField(
            model_name='case',
            name='lead_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_cases', to=settings.AUTH_USER_MODEL, verbose_name='Fallverantwortlich'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am'),
        ),
    ]
