# Generated by Django 5.1.15 on 2026-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_completed_at_description_lead_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fieldtemplate',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='unique_facility_fieldtemplate_name'),
        ),
    ]
