# Generated by Django 5.1.15 on 2026-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_eventhistory_append_only_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='min_contact_stage',
            field=models.CharField(blank=True, choices=[('identified', 'Identifiziert'), ('qualified', 'Qualifiziert')], max_length=20, null=True, verbose_name='Mindest-Kontaktstufe'),
        ),
    ]
