# Generated by Django 5.1.15 on 2026-03-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_choices_to_min_contact_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Arbeitsauftrag', 'verbose_name_plural': 'Arbeitsaufträge'},
        ),
        migrations.AlterField(
            model_name='deletionrequest',
            name='target_type',
            field=models.CharField(choices=[('Event', 'Event')], max_length=100, verbose_name='Zieltyp'),
        ),
    ]
