# Generated by Django 5.1.15 on 2026-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_target_type_choices'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deletionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('requested_by', models.F('reviewed_by')), _negated=True), name='deletion_request_different_reviewer'),
        ),
    ]
