# Generated by Django 5.1.15 on 2026-03-21 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_deletion_request_self_approval_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.facility', verbose_name='Einrichtung'),
        ),
    ]
