# Generated by Django 5.1.15 on 2026-03-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_auditlog_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='system_type',
            field=models.CharField(blank=True, choices=[('ban', 'Hausverbot'), ('contact', 'Kontakt'), ('crisis', 'Krisengespräch'), ('medical', 'Medizinische Versorgung'), ('needle_exchange', 'Spritzentausch'), ('accompaniment', 'Begleitung'), ('counseling', 'Beratungsgespräch'), ('referral', 'Vermittlung'), ('note', 'Notiz')], help_text='Interner Typ für systemgesteuerte Logik (Hausverbot, Export etc.)', max_length=30, null=True, verbose_name='Systemtyp'),
        ),
    ]
