# Generated by Django 5.1.15 on 2026-03-21 22:15

from django.db import migrations


def populate_system_type(apps, schema_editor):
    DocumentType = apps.get_model("core", "DocumentType")
    mapping = {
        "Hausverbot": "ban",
        "Kontakt": "contact",
        "Krisengespräch": "crisis",
        "Medizinische Versorgung": "medical",
        "Spritzentausch": "needle_exchange",
        "Begleitung": "accompaniment",
        "Beratungsgespräch": "counseling",
        "Vermittlung": "referral",
        "Notiz": "note",
    }
    for name, sys_type in mapping.items():
        DocumentType.objects.filter(name=name).update(system_type=sys_type)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_documenttype_system_type'),
    ]

    operations = [
        migrations.RunPython(populate_system_type, migrations.RunPython.noop),
    ]
