# Generated by Django 5.1.15 on 2026-03-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_populate_system_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtemplate',
            name='slug',
            field=models.SlugField(default='', help_text='Stabiler Identifier — wird als Key in data_json verwendet. Nach Erstellung unveränderbar.', max_length=120, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='fieldtemplate',
            constraint=models.UniqueConstraint(fields=('facility', 'slug'), name='unique_facility_fieldtemplate_slug'),
        ),
    ]
