# Generated by Django 5.1.15 on 2026-03-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_fieldtemplate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Zu erledigen bis'),
        ),
    ]
