# Generated by Django 5.1.15 on 2026-03-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_case_client'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "UPDATE core_auditlog SET detail = '{}' WHERE detail = '' OR detail IS NULL;"
                " UPDATE core_auditlog SET detail = json_build_object('text', detail)::text"
                " WHERE detail != '{}' AND detail NOT LIKE '{%%' AND detail NOT LIKE '[%%';"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='detail',
            field=models.JSONField(blank=True, default=dict, verbose_name='Details'),
        ),
    ]
