# Generated by Django 5.1.15 on 2026-03-22 19:42

from django.db import migrations


def convert_text_to_json(apps, schema_editor):
    """Convert existing text detail values to JSON dicts.

    - Empty string / None -> {} (already handled by JSONField default)
    - Non-empty string -> {"text": "<old_value>"}
    """
    AuditLog = apps.get_model("core", "AuditLog")
    for entry in AuditLog.objects.all().iterator():
        if isinstance(entry.detail, str):
            if entry.detail.strip():
                entry.detail = {"text": entry.detail}
            else:
                entry.detail = {}
            entry.save(update_fields=["detail"])


def revert_json_to_text(apps, schema_editor):
    """Revert JSON dicts back to text for reverse migration."""
    AuditLog = apps.get_model("core", "AuditLog")
    for entry in AuditLog.objects.all().iterator():
        if isinstance(entry.detail, dict):
            entry.detail = entry.detail.get("text", "")
            entry.save(update_fields=["detail"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_audit_detail_jsonfield"),
    ]

    operations = [
        migrations.RunPython(convert_text_to_json, revert_json_to_text),
    ]
