# Generated by Django 5.1.15 on 2026-03-24 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auditlog_immutable_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('started_at', models.DateField(verbose_name='Beginn')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Ende')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.case', verbose_name='Fall')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_episodes', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episoden',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.episode', verbose_name='Episode'),
        ),
    ]
