# Generated by Django 5.1.15 on 2026-03-24 01:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0024_auditlog_immutable_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('created', 'erstellt'), ('updated', 'aktualisiert'), ('deleted', 'gelöscht'), ('qualified', 'qualifiziert'), ('completed', 'erledigt'), ('reopened', 'wiedereröffnet')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.facility')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Aktivität',
                'verbose_name_plural': 'Aktivitäten',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['facility', '-occurred_at'], name='core_activi_facilit_0d10e9_idx'), models.Index(fields=['target_type', 'target_id'], name='core_activi_target__9854d1_idx')],
            },
        ),
    ]
