# Generated by Django 5.1.15 on 2026-03-24 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_episode_model_event_episode_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='Erreicht')),
                ('achieved_at', models.DateField(blank=True, null=True, verbose_name='Erreicht am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wirkungsziel',
                'verbose_name_plural': 'Wirkungsziele',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Abgeschlossen')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.outcomegoal')),
            ],
            options={
                'verbose_name': 'Meilenstein',
                'verbose_name_plural': 'Meilensteine',
                'ordering': ['sort_order'],
            },
        ),
    ]
