# Generated by Django 5.1.15 on 2026-03-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_activity'),
        ('core', '0026_outcomegoal_milestone'),
    ]

    operations = [
    ]
