# Generated by Django 5.1.15 on 2026-03-24 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_0025_activity_0026_outcomegoal_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widgets', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard-Einstellung',
                'verbose_name_plural': 'Dashboard-Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='RecentClientVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visited_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_visits', to='core.client')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_client_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Klienten-Besuch',
                'verbose_name_plural': 'Klienten-Besuche',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['user', 'facility', '-visited_at'], name='core_recent_user_id_9acc1e_idx')],
                'unique_together': {('user', 'client')},
            },
        ),
    ]
