# Generated by Django 5.1.15 on 2026-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_dashboardpreference_recentclientvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='retention_activities_days',
            field=models.IntegerField(default=365, verbose_name='Aufbewahrung Aktivitäten (Tage)'),
        ),
    ]
