# Generated by Django 5.1.15 on 2026-03-25 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_settings_retention_activities_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='lead_user',
            field=models.ForeignKey(blank=True, help_text='Hauptverantwortliche Fachkraft für diesen Fall', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_cases', to=settings.AUTH_USER_MODEL, verbose_name='Fallverantwortlich'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('closed', 'Geschlossen')], default='open', help_text='Offen = aktiver Fall, Geschlossen = abgeschlossen', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age_cluster',
            field=models.CharField(choices=[('u18', 'Unter 18'), ('18_26', '18–26'), ('27_plus', '27+'), ('unknown', 'Unbekannt')], default='unknown', help_text='Altersgruppe des Klienten zum Zeitpunkt der Erfassung', max_length=20, verbose_name='Altersgruppe'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_stage',
            field=models.CharField(choices=[('identified', 'Identifiziert'), ('qualified', 'Qualifiziert')], default='identified', help_text='Identifiziert = Pseudonym bekannt, Qualifiziert = vollständige Identität bekannt', max_length=20, verbose_name='Kontaktstufe'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Interne Notizen, nur für Fachkräfte sichtbar', verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='timefilter',
            name='end_time',
            field=models.TimeField(help_text='Schichtende (z.B. 16:00). Bei Nachtschicht: Ende nach Mitternacht möglich', verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='timefilter',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Wird als Standard-Schicht vorausgewählt, wenn keine aktive Schicht erkannt wird', verbose_name='Standard'),
        ),
        migrations.AlterField(
            model_name='timefilter',
            name='start_time',
            field=models.TimeField(help_text='Schichtbeginn (z.B. 08:00)', verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='item_type',
            field=models.CharField(choices=[('hint', 'Hinweis'), ('task', 'Aufgabe')], default='task', help_text='Kategorisierung der Aufgabe (Aufgabe, Telefonat, Termin etc.)', max_length=10, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('important', 'Wichtig'), ('urgent', 'Dringend')], default='normal', help_text='Dringend = sofortige Bearbeitung, Wichtig = zeitnah, Normal = regulär', max_length=20, verbose_name='Priorität'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('done', 'Erledigt'), ('dismissed', 'Verworfen')], default='open', help_text='Offen = noch nicht begonnen, In Bearbeitung = aktiv, Erledigt = abgeschlossen', max_length=20, verbose_name='Status'),
        ),
    ]
