# Generated by Django 5.1.15 on 2026-03-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_case_lead_user_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='category',
            field=models.CharField(choices=[('contact', 'Kontakt'), ('service', 'Leistung'), ('admin', 'Verwaltung'), ('note', 'Notiz')], default='contact', help_text='Gruppiert Dokumentationstypen für Filter und Auswertungen', max_length=20, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='min_contact_stage',
            field=models.CharField(blank=True, choices=[('identified', 'Identifiziert'), ('qualified', 'Qualifiziert')], help_text='Mindest-Kontaktstufe des Klienten für diesen Dokumentationstyp', max_length=20, null=True, verbose_name='Mindest-Kontaktstufe'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='sensitivity',
            field=models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Erhöht'), ('high', 'Hoch')], default='normal', help_text='Steuert Zugriffsrechte: ELEVATED/HIGH erfordern höhere Berechtigungen', max_length=20, verbose_name='Sensibilität'),
        ),
    ]
