# Generated by Django 5.1.15 on 2026-03-26 21:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_documenttype_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('data', models.JSONField(default=dict)),
                ('jugendamt_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_snapshots', to='core.facility')),
            ],
            options={
                'verbose_name': 'Statistik-Snapshot',
                'verbose_name_plural': 'Statistik-Snapshots',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('facility', 'year', 'month'), name='unique_snapshot_per_month')],
            },
        ),
    ]
