# Generated by Django 5.1.15 on 2026-03-28 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_statisticssnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['pseudonym'], 'verbose_name': 'Klientel', 'verbose_name_plural': 'Klientel'},
        ),
        migrations.AlterModelOptions(
            name='recentclientvisit',
            options={'ordering': ['-visited_at'], 'verbose_name': 'Klientel-Besuch', 'verbose_name_plural': 'Klientel-Besuche'},
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='core.client', verbose_name='Klientel'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age_cluster',
            field=models.CharField(choices=[('u18', 'Unter 18'), ('18_26', '18–26'), ('27_plus', '27+'), ('unknown', 'Unbekannt')], default='unknown', help_text='Altersgruppe des Klientel zum Zeitpunkt der Erfassung', max_length=20, verbose_name='Altersgruppe'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='min_contact_stage',
            field=models.CharField(blank=True, choices=[('identified', 'Identifiziert'), ('qualified', 'Qualifiziert')], help_text='Mindest-Kontaktstufe des Klientel für diesen Dokumentationstyp', max_length=20, null=True, verbose_name='Mindest-Kontaktstufe'),
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.client', verbose_name='Klientel'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='core.client', verbose_name='Klientel'),
        ),
    ]
