# Generated by Django 5.1.15 on 2026-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_client_options_alter_recentclientvisit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=5, verbose_name='Bevorzugte Sprache'),
        ),
    ]
