# Generated by Django 5.1.15 on 2026-04-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_fix_anonymous_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtemplate',
            name='sensitivity',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('elevated', 'Erhöht'), ('high', 'Hoch')], default='', help_text='Feld-Level Sichtbarkeit. Leer = erbt vom Dokumentationstyp.', max_length=20, verbose_name='Sensibilität'),
        ),
    ]
