# Generated by Django 5.1.15 on 2026-04-05 23:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_migrate_encrypted_to_sensitivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='allowed_file_types',
            field=models.CharField(blank=True, default='pdf,jpg,jpeg,png,docx', help_text='Kommagetrennte Dateiendungen (z.B. pdf,jpg,png,docx)', max_length=500, verbose_name='Erlaubte Dateitypen'),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=10, verbose_name='Max. Dateigröße (MB)'),
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textbereich'), ('number', 'Zahl'), ('date', 'Datum'), ('time', 'Uhrzeit'), ('boolean', 'Ja/Nein'), ('select', 'Auswahl'), ('multi_select', 'Mehrfachauswahl'), ('file', 'Datei')], default='text', max_length=20, verbose_name='Feldtyp'),
        ),
        migrations.CreateModel(
            name='EventAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_filename', models.CharField(help_text='UUID-basierter Dateiname auf Disk (z.B. abcd1234.enc)', max_length=255, verbose_name='Speicherdateiname')),
                ('original_filename_encrypted', models.JSONField(help_text='Verschlüsselt via encrypt_field()', verbose_name='Originaldateiname (verschlüsselt)')),
                ('file_size', models.PositiveIntegerField(verbose_name='Dateigröße (Bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME-Typ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.event', verbose_name='Event')),
                ('field_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.fieldtemplate', verbose_name='Feldvorlage')),
            ],
            options={
                'verbose_name': 'Dateianhang',
                'verbose_name_plural': 'Dateianhänge',
                'ordering': ['-created_at'],
            },
        ),
    ]
