# Generated by Django 5.1.15 on 2026-04-06 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_file_vault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('login_failed', 'Anmeldung fehlgeschlagen'), ('view_qualified', 'Qualifizierte Daten eingesehen'), ('export', 'Export'), ('delete', 'Löschung'), ('stage_change', 'Stufenwechsel'), ('settings_change', 'Einstellungen geändert'), ('download', 'Download'), ('legal_hold', 'Legal Hold')], max_length=30, verbose_name='Aktion'),
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=100, verbose_name='Zieltyp')),
                ('target_id', models.UUIDField(verbose_name='Ziel-ID')),
                ('reason', models.TextField(verbose_name='Begründung')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Ablaufdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Aufgehoben am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_holds', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_holds', to=settings.AUTH_USER_MODEL, verbose_name='Aufgehoben von')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_holds', to='core.facility', verbose_name='Einrichtung')),
            ],
            options={
                'verbose_name': 'Legal Hold',
                'verbose_name_plural': 'Legal Holds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('Event', 'Event')], max_length=100, verbose_name='Zieltyp')),
                ('target_id', models.UUIDField(verbose_name='Ziel-ID')),
                ('proposed_at', models.DateTimeField(auto_now_add=True, verbose_name='Vorgeschlagen am')),
                ('deletion_due_at', models.DateField(verbose_name='Löschfrist')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Freigegeben'), ('held', 'Aufgeschoben')], default='pending', max_length=20, verbose_name='Status')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('retention_category', models.CharField(help_text='anonymous, identified, qualified oder document_type', max_length=50, verbose_name='Kategorie')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_proposals', to='core.facility', verbose_name='Einrichtung')),
            ],
            options={
                'verbose_name': 'Löschvorschlag',
                'verbose_name_plural': 'Löschvorschläge',
                'ordering': ['deletion_due_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'held'])), fields=('facility', 'target_type', 'target_id'), name='unique_active_retention_proposal')],
            },
        ),
    ]
