# Generated by Django 5.1.15 on 2026-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_auditlog_action_legalhold_retentionproposal'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deletionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('facility', 'target_type', 'target_id'), name='unique_pending_deletion_request'),
        ),
    ]
