# Generated by Django 5.1.15 on 2026-04-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_deletionrequest_unique_pending_deletion_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offline_key_salt',
            field=models.CharField(blank=True, default='', help_text='Base64URL-Salt für die client-seitige PBKDF2-Ableitung. Lazy generiert beim ersten Salt-Endpoint-Aufruf, rotiert bei Passwort-Änderung.', max_length=32, verbose_name='Offline-Schlüssel-Salt'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('login_failed', 'Anmeldung fehlgeschlagen'), ('view_qualified', 'Qualifizierte Daten eingesehen'), ('export', 'Export'), ('delete', 'Löschung'), ('stage_change', 'Stufenwechsel'), ('settings_change', 'Einstellungen geändert'), ('download', 'Download'), ('legal_hold', 'Legal Hold'), ('offline_key_fetch', 'Offline-Schlüssel abgerufen')], max_length=30, verbose_name='Aktion'),
        ),
    ]
