# Generated by Django 5.1.15 on 2026-04-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_offline_key_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhistory',
            name='field_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot der Feld-Labels, Sensitivität und Verschlüsselungsstatus zum Zeitpunkt der Änderung für revisionsfeste Darstellung.'),
        ),
    ]
