# Generated by Django 5.1.15 on 2026-04-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auditlog_security_violation_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='mfa_enforced_facility_wide',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, gilt MFA-Zwang (TOTP) automatisch für alle Nutzer dieser Einrichtung — unabhängig vom einzelnen Benutzerfeld mfa_required.', verbose_name='2FA-Pflicht für alle Nutzer'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_required',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, muss der Nutzer ein TOTP-Gerät einrichten, bevor er die Anwendung weiter nutzen kann. Wird automatisch gesetzt, wenn die Einrichtung 2FA für alle verlangt.', verbose_name='2FA erforderlich'),
        ),
    ]
