# Generated by Django 5.1.15 on 2026-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_postgres_rls_setup'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='retentionproposal',
            name='unique_active_retention_proposal',
        ),
        migrations.AddField(
            model_name='retentionproposal',
            name='defer_count',
            field=models.PositiveIntegerField(default=0, help_text='Wie oft wurde der Vorschlag bereits zurückgestellt.', verbose_name='Anzahl Zurückstellungen'),
        ),
        migrations.AddField(
            model_name='retentionproposal',
            name='deferred_until',
            field=models.DateField(blank=True, help_text='Datum, ab dem ein zurückgestellter Vorschlag wieder vorgelegt wird.', null=True, verbose_name='Wiedervorlage am'),
        ),
        migrations.AddField(
            model_name='settings',
            name='retention_auto_approve_after_defer',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, werden Löschvorschläge nach Überschreiten der maximalen Zurückstellungszahl automatisch freigegeben, statt manuelle Entscheidung zu erzwingen.', verbose_name='Auto-Freigabe nach mehrfacher Zurückstellung'),
        ),
        migrations.AddField(
            model_name='settings',
            name='retention_max_defer_count',
            field=models.PositiveIntegerField(default=2, help_text='Nach wie vielen Zurückstellungen eine endgültige Entscheidung erzwungen oder (bei Auto-Freigabe) automatisch freigegeben wird.', verbose_name='Maximale Zurückstellungen'),
        ),
        migrations.AlterField(
            model_name='retentionproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Freigegeben'), ('held', 'Legal Hold'), ('deferred', 'Zurückgestellt'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='retentionproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'held', 'deferred'])), fields=('facility', 'target_type', 'target_id'), name='unique_active_retention_proposal'),
        ),
    ]
