# Generated by Django 5.1.15 on 2026-04-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_retention_defer_and_bulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='k_anonymized',
            field=models.BooleanField(default=False, help_text='Kennzeichnet, ob der Datensatz per K-Anonymisierung generalisiert wurde (Alternative zu Hard-Delete für Langzeit-Statistik).', verbose_name='K-anonymisiert'),
        ),
        migrations.AddField(
            model_name='settings',
            name='k_anonymity_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Mindest-Gruppengröße für K-Anonymität (z.B. k=5 → mindestens 5 Datensätze pro Bucket). Je höher der Wert, desto stärker die Anonymisierung.', verbose_name='K-Anonymitäts-Schwelle'),
        ),
        migrations.AddField(
            model_name='settings',
            name='retention_use_k_anonymization',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, wird bei DSGVO-Löschung statt Hard-Delete eine K-Anonymisierung durchgeführt. Der Datensatz bleibt statistisch auswertbar, ist aber nicht mehr re-identifizierbar.', verbose_name='K-Anonymisierung statt Hard-Delete'),
        ),
    ]
