# Generated by Django 5.1.15 on 2026-04-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_fieldtemplate_is_active'),
        ('core', '0050_quick_template'),
    ]

    operations = [
    ]
