# Generated by Django 5.1.15 on 2026-04-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_optimistic_locking_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="remind_at",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Optional. Wann soll das Workitem wieder aufpoppen?",
                null=True,
                verbose_name="Wiedervorlage am",
            ),
        ),
    ]
