# Generated by Django 5.1.15 on 2026-04-19 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_pg_trgm_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='search_trigram_threshold',
            field=models.FloatField(default=0.3, help_text='Mindest-Ähnlichkeit (0.0–1.0) für Fuzzy-Treffer im Pseudonym. Kleinere Werte liefern mehr, aber ungenauere Treffer; größere Werte sind strenger. Standard: 0.3.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Fuzzy-Search-Schwelle'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(condition=models.Q(('search_trigram_threshold__gte', 0.0), ('search_trigram_threshold__lte', 1.0)), name='settings_trigram_threshold_range'),
        ),
    ]
