# Generated by Django 5.1.15 on 2026-04-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardPreference',
        ),
    ]
