# Generated by Django 5.1.15 on 2026-04-23 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_rls_outcome_milestone_dtf'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattachment',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='Aktuelle Version'),
        ),
        migrations.AddField(
            model_name='eventattachment',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ersetzt am'),
        ),
        migrations.AddField(
            model_name='eventattachment',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prior_versions', to='core.eventattachment', verbose_name='Ersetzt durch'),
        ),
    ]
