# Generated by Django 5.1.15 on 2026-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_attachment_versioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='remind_at',
            field=models.DateField(blank=True, db_index=True, help_text='Optional. Wann soll die Aufgabe wieder aufpoppen?', null=True, verbose_name='Wiedervorlage am'),
        ),
    ]
