# Generated by Django 5.1.15 on 2026-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_workitem_remind_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['facility', '-timestamp'], name='auditlog_facility_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='auditlog_action_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='auditlog_user_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='case_facility_status_ca_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['facility', 'is_deleted', '-occurred_at'], name='event_facility_del_occ_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['facility', 'status', '-created_at'], name='workitem_facility_status_idx'),
        ),
    ]
