# Generated by Django 5.1.15 on 2026-04-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auditlog_auditlog_facility_ts_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtemplate',
            name='default_value',
            field=models.TextField(blank=True, default='', help_text='Wird beim Neu-Anlegen eines Ereignisses vorgeblendet. Leer lassen = kein Default. Für SELECT/MULTI_SELECT: Option-Slug(s) (mehrere durch Komma trennen). Für FILE nicht unterstützt.', verbose_name='Default-Wert'),
        ),
    ]
