# Generated by Django 5.1.15 on 2026-04-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_attachment_versioning_stage_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('login_failed', 'Anmeldung fehlgeschlagen'), ('login_unlock', 'Account-Sperre aufgehoben'), ('view_qualified', 'Qualifizierte Daten eingesehen'), ('export', 'Export'), ('delete', 'Löschung'), ('stage_change', 'Stufenwechsel'), ('settings_change', 'Einstellungen geändert'), ('download', 'Download'), ('legal_hold', 'Legal Hold'), ('offline_key_fetch', 'Offline-Schlüssel abgerufen'), ('client_create', 'Klientel angelegt'), ('client_update', 'Klientel aktualisiert'), ('case_create', 'Fall angelegt'), ('case_update', 'Fall aktualisiert'), ('case_close', 'Fall geschlossen'), ('case_reopen', 'Fall wiedereröffnet'), ('milestone_delete', 'Meilenstein gelöscht'), ('event_create', 'Ereignis angelegt'), ('workitem_create', 'Aufgabe angelegt'), ('workitem_update', 'Aufgabe aktualisiert'), ('user_role_changed', 'Benutzerrolle geändert'), ('user_deactivated', 'Benutzer deaktiviert'), ('password_reset_requested', 'Passwort-Reset angefordert'), ('security_violation', 'Sicherheitsverletzung'), ('mfa_enabled', '2FA aktiviert'), ('mfa_disabled', '2FA deaktiviert'), ('mfa_failed', '2FA-Verifikation fehlgeschlagen'), ('backup_codes_generated', '2FA Backup-Codes generiert'), ('backup_codes_used', '2FA Backup-Code verwendet'), ('backup_codes_regenerated', '2FA Backup-Codes neu generiert')], max_length=30, verbose_name='Aktion'),
        ),
    ]
