# Generated by Django 5.1.15 on 2026-04-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auditlog_case_close_reopen_milestone_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='item_type',
            field=models.CharField(choices=[('hint', 'Hinweis'), ('task', 'Aufgabe')], default='task', help_text='Aufgabe = aktiv zu erledigen, Hinweis = informativ.', max_length=10, verbose_name='Typ'),
        ),
    ]
