# Generated by Django 6.0.4 on 2026-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_fieldtemplate_high_sensitivity_heal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="category",
            field=models.CharField(
                choices=[("contact", "Kontakt"), ("service", "Leistung"), ("admin", "Verwaltung"), ("note", "Notiz")],
                default="contact",
                help_text="Reine UI-Gruppierung für Statistik-Anzeige und Admin-Filter. Beeinflusst weder Export noch Bann-/Krisen-Logik — dafür ist der Systemtyp zuständig.",
                max_length=20,
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="system_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ban", "Hausverbot"),
                    ("contact", "Kontakt"),
                    ("crisis", "Krisengespräch"),
                    ("medical", "Medizinische Versorgung"),
                    ("needle_exchange", "Spritzentausch"),
                    ("accompaniment", "Begleitung"),
                    ("counseling", "Beratungsgespräch"),
                    ("referral", "Vermittlung"),
                    ("note", "Notiz"),
                ],
                help_text="Stabile Kennung für Bann-Logik, Krisen-Highlight und Jugendamt-Export. Nach Erstellung unveränderbar.",
                max_length=30,
                null=True,
                verbose_name="Systemtyp",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttype",
            constraint=models.UniqueConstraint(
                fields=("facility", "name", "category"), name="unique_facility_documenttype_name_category"
            ),
        ),
    ]
