# Generated by Django 6.0.4 on 2026-04-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_documenttype_unique_constraint_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='auditlog_retention_months',
            field=models.PositiveIntegerField(default=24, help_text='Wie lange AuditLog-Eintraege aufbewahrt werden, bevor das enforce_retention-Kommando sie loescht. 0 = deaktiviert (unbegrenzte Aufbewahrung).', verbose_name='AuditLog-Aufbewahrung (Monate)'),
        ),
    ]
