# Generated by Django 6.0.4 on 2026-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_redact_legacy_eventhistory_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, help_text='Frei-Text-Beschreibung des Falls. Nicht feldverschlüsselt — keine Klarnamen oder Art-9-Daten hier vermerken; sensible Inhalte gehören in ein Event-FieldTemplate mit Sensitivity=HOCH.', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Interne Notizen, nur für Fachkräfte sichtbar. **Nicht feldverschlüsselt** — keine Klarnamen / Art-9-Daten (Gesundheit, Suchtdiagnosen, Klarname-Adresse) hier vermerken. Sensible Inhalte gehören in ein FieldTemplate mit Sensitivity=HOCH.', verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, help_text='Frei-Text-Beschreibung der Episode. Nicht feldverschlüsselt — keine Klarnamen oder Art-9-Daten hier vermerken.', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='description',
            field=models.TextField(blank=True, help_text='Frei-Text-Beschreibung der Aufgabe. Nicht feldverschlüsselt — keine Klarnamen oder Art-9-Daten hier vermerken.', verbose_name='Beschreibung'),
        ),
    ]
