# Generated by Django 6.0.4 on 2026-04-30 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_client_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am'),
        ),
        migrations.AddField(
            model_name='case',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gelöscht von'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Gelöscht'),
        ),
        migrations.AddField(
            model_name='episode',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am'),
        ),
        migrations.AddField(
            model_name='episode',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gelöscht von'),
        ),
        migrations.AddField(
            model_name='episode',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Gelöscht'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gelöscht von'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Gelöscht'),
        ),
    ]
