# Generated by Django 6.0.4 on 2026-04-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_case_episode_workitem_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='client_trash_days',
            field=models.PositiveIntegerField(default=30, help_text='Wie lange soft-deletete Personen im Papierkorb verbleiben, bevor enforce_retention sie automatisch anonymisiert. Während dieser Frist kann ein Admin den Datensatz wiederherstellen.', verbose_name='Papierkorb-Frist (Tage)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('login_failed', 'Anmeldung fehlgeschlagen'), ('login_unlock', 'Account-Sperre aufgehoben'), ('view_qualified', 'Qualifizierte Daten eingesehen'), ('export', 'Export'), ('delete', 'Löschung'), ('stage_change', 'Stufenwechsel'), ('settings_change', 'Einstellungen geändert'), ('download', 'Download'), ('legal_hold', 'Legal Hold'), ('offline_key_fetch', 'Offline-Schlüssel abgerufen'), ('client_create', 'Person angelegt'), ('client_update', 'Person aktualisiert'), ('client_soft_deleted', 'Person in Papierkorb'), ('client_restored', 'Person wiederhergestellt'), ('client_anonymized', 'Person anonymisiert'), ('case_create', 'Fall angelegt'), ('case_update', 'Fall aktualisiert'), ('case_close', 'Fall geschlossen'), ('case_reopen', 'Fall wiedereröffnet'), ('milestone_delete', 'Meilenstein gelöscht'), ('event_create', 'Ereignis angelegt'), ('workitem_create', 'Aufgabe angelegt'), ('workitem_update', 'Aufgabe aktualisiert'), ('user_role_changed', 'Benutzerrolle geändert'), ('user_deactivated', 'Benutzer deaktiviert'), ('password_reset_requested', 'Passwort-Reset angefordert'), ('security_violation', 'Sicherheitsverletzung'), ('mfa_enabled', '2FA aktiviert'), ('mfa_disabled', '2FA deaktiviert'), ('mfa_failed', '2FA-Verifikation fehlgeschlagen'), ('backup_codes_generated', '2FA Backup-Codes generiert'), ('backup_codes_used', '2FA Backup-Code verwendet'), ('backup_codes_regenerated', '2FA Backup-Codes neu generiert'), ('sudo_mode_entered', 'Sudo-Mode aktiviert (Re-Auth)')], max_length=30, verbose_name='Aktion'),
        ),
        migrations.AlterField(
            model_name='deletionrequest',
            name='target_type',
            field=models.CharField(choices=[('Event', 'Event'), ('Client', 'Person')], max_length=100, verbose_name='Zieltyp'),
        ),
    ]
