# Generated by Django 6.0.4 on 2026-05-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_add_event_search_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['pseudonym'], 'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
        migrations.AlterModelOptions(
            name='recentclientvisit',
            options={'ordering': ['-visited_at'], 'verbose_name': 'Personen-Besuch', 'verbose_name_plural': 'Personen-Besuche'},
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(help_text='Pflichtfeld: Jeder Fall ist einer Person zugeordnet. PROTECT verhindert versehentliches Löschen einer Person mit aktiven Fällen.', on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='core.client', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age_cluster',
            field=models.CharField(choices=[('u18', 'Unter 18'), ('18_26', '18–26'), ('27_plus', '27+'), ('unknown', 'Unbekannt')], default='unknown', help_text='Altersgruppe der Person zum Zeitpunkt der Erfassung', max_length=20, verbose_name='Altersgruppe'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='min_contact_stage',
            field=models.CharField(blank=True, choices=[('identified', 'Identifiziert'), ('qualified', 'Qualifiziert')], help_text='Mindest-Kontaktstufe der Person für diesen Dokumentationstyp', max_length=20, null=True, verbose_name='Mindest-Kontaktstufe'),
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.client', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='core.client', verbose_name='Person'),
        ),
    ]
