# Generated by Django 6.0.6 on 2026-06-11 18:37
#
# Refs #1053 (Variante A): Recht "Löschbestätigung" entkoppelt den
# Vier-Augen-Genehmiger-Pool vom Rollenmodell. Backfill: bestehende
# Leitungen + Anwendungsbetreuungen behalten ihre Genehmiger-Fähigkeit
# (kein Verhaltensbruch); danach kuratiert die Einrichtung den Pool.

from django.db import migrations, models


def grant_to_existing_leads_and_admins(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(role__in=("facility_admin", "lead")).update(can_confirm_deletion=True)


def revoke_all(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.update(can_confirm_deletion=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_cache_table_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_confirm_deletion',
            field=models.BooleanField(default=False, help_text='Darf Löschanträge als zweite Person genehmigen (Vier-Augen-Prinzip). Rollenunabhängig vergebbar, damit auch bei einer einzelnen Leitung ein Genehmiger verfügbar ist. Eigene Anträge bleiben ausgeschlossen.', verbose_name='Löschbestätigung'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('login_failed', 'Anmeldung fehlgeschlagen'), ('login_unlock', 'Account-Sperre aufgehoben'), ('view_qualified', 'Qualifizierte Daten eingesehen'), ('export', 'Export'), ('delete', 'Löschung'), ('stage_change', 'Stufenwechsel'), ('settings_change', 'Einstellungen geändert'), ('download', 'Download'), ('legal_hold', 'Legal Hold'), ('offline_key_fetch', 'Offline-Schlüssel abgerufen'), ('client_create', 'Person angelegt'), ('client_update', 'Person aktualisiert'), ('client_soft_deleted', 'Person in Papierkorb'), ('client_restored', 'Person wiederhergestellt'), ('client_anonymized', 'Person anonymisiert'), ('case_create', 'Fall angelegt'), ('case_update', 'Fall aktualisiert'), ('case_close', 'Fall geschlossen'), ('case_reopen', 'Fall wiedereröffnet'), ('milestone_delete', 'Meilenstein gelöscht'), ('event_create', 'Ereignis angelegt'), ('workitem_create', 'Aufgabe angelegt'), ('workitem_update', 'Aufgabe aktualisiert'), ('user_role_changed', 'Benutzerrolle geändert'), ('user_deactivated', 'Benutzer deaktiviert'), ('deletion_confirmer_changed', 'Recht Löschbestätigung geändert'), ('password_reset_requested', 'Passwort-Reset angefordert'), ('security_violation', 'Sicherheitsverletzung'), ('mfa_enabled', '2FA aktiviert'), ('mfa_disabled', '2FA deaktiviert'), ('mfa_failed', '2FA-Verifikation fehlgeschlagen'), ('backup_codes_generated', '2FA Backup-Codes generiert'), ('backup_codes_used', '2FA Backup-Code verwendet'), ('backup_codes_regenerated', '2FA Backup-Codes neu generiert'), ('sudo_mode_entered', 'Sudo-Mode aktiviert (Re-Auth)'), ('system_view', 'Systembereich aufgerufen'), ('audit_export', 'Audit-Log exportiert'), ('maintenance_enabled', 'Wartungsmodus aktiviert'), ('maintenance_disabled', 'Wartungsmodus deaktiviert'), ('retention_run_completed', 'Retention-Lauf abgeschlossen'), ('restore_verified', 'Restore-Test verifiziert'), ('deletion_requested', 'Löschung beantragt'), ('deletion_approved', 'Löschung genehmigt'), ('deletion_rejected', 'Löschung abgelehnt'), ('snapshot_run_completed', 'Statistik-Snapshot-Lauf abgeschlossen'), ('breach_scan_completed', 'Breach-Detection-Scan abgeschlossen'), ('mv_refresh_completed', 'Statistik-View-Refresh abgeschlossen')], max_length=30, verbose_name='Aktion'),
        ),
        migrations.RunPython(grant_to_existing_leads_and_admins, revoke_all),
    ]
