# Generated by Django 6.0.6 on 2026-06-12 23:40
#
# Refs #1084 (S2): neue AuditLog-Action SUDO_MODE_FAILED — fehlgeschlagene
# Sudo-Re-Auth wird jetzt auditiert (symmetrisch zu LOGIN_FAILED/MFA_FAILED).
# Reine Choices-Aenderung, DB-seitig wirkungslos.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_user_can_confirm_deletion_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('login_failed', 'Anmeldung fehlgeschlagen'), ('login_unlock', 'Account-Sperre aufgehoben'), ('view_qualified', 'Qualifizierte Daten eingesehen'), ('export', 'Export'), ('delete', 'Löschung'), ('stage_change', 'Stufenwechsel'), ('settings_change', 'Einstellungen geändert'), ('download', 'Download'), ('legal_hold', 'Legal Hold'), ('offline_key_fetch', 'Offline-Schlüssel abgerufen'), ('client_create', 'Person angelegt'), ('client_update', 'Person aktualisiert'), ('client_soft_deleted', 'Person in Papierkorb'), ('client_restored', 'Person wiederhergestellt'), ('client_anonymized', 'Person anonymisiert'), ('case_create', 'Fall angelegt'), ('case_update', 'Fall aktualisiert'), ('case_close', 'Fall geschlossen'), ('case_reopen', 'Fall wiedereröffnet'), ('milestone_delete', 'Meilenstein gelöscht'), ('event_create', 'Ereignis angelegt'), ('workitem_create', 'Aufgabe angelegt'), ('workitem_update', 'Aufgabe aktualisiert'), ('user_role_changed', 'Benutzerrolle geändert'), ('user_deactivated', 'Benutzer deaktiviert'), ('deletion_confirmer_changed', 'Recht Löschbestätigung geändert'), ('password_reset_requested', 'Passwort-Reset angefordert'), ('security_violation', 'Sicherheitsverletzung'), ('mfa_enabled', '2FA aktiviert'), ('mfa_disabled', '2FA deaktiviert'), ('mfa_failed', '2FA-Verifikation fehlgeschlagen'), ('backup_codes_generated', '2FA Backup-Codes generiert'), ('backup_codes_used', '2FA Backup-Code verwendet'), ('backup_codes_regenerated', '2FA Backup-Codes neu generiert'), ('sudo_mode_entered', 'Sudo-Mode aktiviert (Re-Auth)'), ('sudo_mode_failed', 'Sudo-Mode Re-Auth fehlgeschlagen'), ('system_view', 'Systembereich aufgerufen'), ('audit_export', 'Audit-Log exportiert'), ('maintenance_enabled', 'Wartungsmodus aktiviert'), ('maintenance_disabled', 'Wartungsmodus deaktiviert'), ('retention_run_completed', 'Retention-Lauf abgeschlossen'), ('restore_verified', 'Restore-Test verifiziert'), ('deletion_requested', 'Löschung beantragt'), ('deletion_approved', 'Löschung genehmigt'), ('deletion_rejected', 'Löschung abgelehnt'), ('snapshot_run_completed', 'Statistik-Snapshot-Lauf abgeschlossen'), ('breach_scan_completed', 'Breach-Detection-Scan abgeschlossen'), ('mv_refresh_completed', 'Statistik-View-Refresh abgeschlossen')], max_length=30, verbose_name='Aktion'),
        ),
    ]
