# Generated by Django 6.0.6 on 2026-06-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattachment',
            name='detected_mime',
            field=models.CharField(blank=True, default='', help_text='Beim Upload per libmagic erkannter (verifizierter) Typ. Maßgeblich beim Download; der browser-gemeldete mime_type dient nur als Fallback für Bestandsanhänge ohne erkannten Typ (Refs #1274).', max_length=100, verbose_name='Verifizierter MIME-Typ'),
        ),
    ]
