# Generated by Django 6.0.6 on 2026-07-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auditlog_hash_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, editable=False, help_text='X-Idempotency-Key des Offline-Replays — persistenter DB-Backstop gegen Duplikate bei Cache-Verlust oder parallelen Replays (Review R5/R6).', max_length=64, null=True, verbose_name='Idempotenz-Schlüssel'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, editable=False, help_text='X-Idempotency-Key des Offline-Replays — persistenter DB-Backstop gegen Duplikate bei Cache-Verlust oder parallelen Replays (Review R5/R6).', max_length=64, null=True, verbose_name='Idempotenz-Schlüssel'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('created_by', 'idempotency_key'), name='event_idem_key_per_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workitem',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('created_by', 'idempotency_key'), name='workitem_idem_key_per_user_uniq'),
        ),
    ]
