# Generated by Django 6.0.6 on 2026-07-07 08:46

import django.core.validators
from django.db import migrations, models


def _clamp_invalid_values(apps, schema_editor):
    """Bestandsdaten unter die neue Untergrenze klemmen (Security N8, Refs #1445).

    Werte < 1 auf den Feld-Default (bzw. 1) heben, sonst scheitert der
    anschliessende CheckConstraint-Add auf Alt-Instanzen mit bereits gesetzten
    0/negativen Fristen.
    """
    Settings = apps.get_model("core", "Settings")
    defaults = {
        "session_timeout_minutes": 30,
        "retention_anonymous_days": 90,
        "retention_identified_days": 365,
        "retention_qualified_days": 3650,
        "retention_activities_days": 365,
    }
    for field, default in defaults.items():
        Settings.objects.filter(**{f"{field}__lt": 1}).update(**{field: default})

    DocumentType = apps.get_model("core", "DocumentType")
    DocumentType.objects.filter(retention_days__lt=1).update(retention_days=1)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_event_idempotency_key_workitem_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='retention_days',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aufbewahrungsfrist (Tage)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='retention_activities_days',
            field=models.IntegerField(default=365, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aufbewahrung Aktivitäten (Tage)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='retention_anonymous_days',
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aufbewahrung anonym (Tage)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='retention_identified_days',
            field=models.IntegerField(default=365, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aufbewahrung identifiziert (Tage)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='retention_qualified_days',
            field=models.IntegerField(default=3650, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Aufbewahrung qualifiziert (Tage)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='session_timeout_minutes',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Session-Timeout (Minuten)'),
        ),
        # Security N8 (Refs #1445): Alt-Daten klemmen, BEVOR die CheckConstraints
        # angehaengt werden — sonst schlaegt AddConstraint auf Instanzen mit
        # bereits gesetzten 0/negativen Fristen fehl.
        migrations.RunPython(_clamp_invalid_values, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.CheckConstraint(condition=models.Q(('retention_days__isnull', True), ('retention_days__gte', 1), _connector='OR'), name='documenttype_retention_days_min_1'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.CheckConstraint(condition=models.Q(('session_timeout_minutes__gte', 1), ('retention_anonymous_days__gte', 1), ('retention_identified_days__gte', 1), ('retention_qualified_days__gte', 1), ('retention_activities_days__gte', 1)), name='settings_retention_days_min_1'),
        ),
    ]
