# Generated by Django 6.0.7 on 2026-07-11 16:17
#
# Refs #1369: additive, nullable ``actor``-FK — der handelnde Admin bei
# ziel-attribuierten Privileg-Events. Bewusst ohne Datenmigration:
# ``ADD COLUMN ... NULL`` ist reines DDL (kein Row-Rewrite, kein UPDATE), also
# vertraeglich mit dem AuditLog-Immutability-Trigger (Migration 0024, greift nur
# fuer UPDATE/DELETE). Bestandszeilen bleiben ``actor=NULL`` und behalten damit
# ihren gespeicherten ``entry_hash`` (die Kette bezieht ``actor_id`` nur ein,
# wenn gesetzt — siehe services/audit/chain.py). Refs #1070.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Handelnde Person'),
        ),
    ]
