"""Retention proposals and legal holds for GDPR retention management."""

import uuid
from datetime import date

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models.managers import FacilityScopedManager


class RetentionProposal(models.Model):
    """Deletion proposal generated by enforce_retention --propose."""

    class Status(models.TextChoices):
        PENDING = "pending", _("Ausstehend")
        APPROVED = "approved", _("Freigegeben")
        HELD = "held", _("Legal Hold")
        DEFERRED = "deferred", _("Zurückgestellt")
        REJECTED = "rejected", _("Abgelehnt")

    class TargetType(models.TextChoices):
        EVENT = "Event", _("Event")

    objects = FacilityScopedManager()

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    facility = models.ForeignKey(
        "core.Facility",
        on_delete=models.CASCADE,
        related_name="retention_proposals",
        verbose_name=_("Einrichtung"),
    )
    target_type = models.CharField(
        max_length=100,
        choices=TargetType.choices,
        verbose_name=_("Zieltyp"),
    )
    target_id = models.UUIDField(verbose_name=_("Ziel-ID"))
    proposed_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Vorgeschlagen am"))
    deletion_due_at = models.DateField(verbose_name=_("Löschfrist"))
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
        verbose_name=_("Status"),
    )
    details = models.JSONField(default=dict, blank=True, verbose_name=_("Details"))
    retention_category = models.CharField(
        max_length=50,
        verbose_name=_("Kategorie"),
        help_text=_("anonymous, identified, qualified oder document_type"),
    )
    deferred_until = models.DateField(
        null=True,
        blank=True,
        verbose_name=_("Wiedervorlage am"),
        help_text=_("Datum, ab dem ein zurückgestellter Vorschlag wieder vorgelegt wird."),
    )
    defer_count = models.PositiveIntegerField(
        default=0,
        verbose_name=_("Anzahl Zurückstellungen"),
        help_text=_("Wie oft wurde der Vorschlag bereits zurückgestellt."),
    )

    class Meta:
        verbose_name = _("Löschvorschlag")
        verbose_name_plural = _("Löschvorschläge")
        ordering = ["deletion_due_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["facility", "target_type", "target_id"],
                condition=models.Q(status__in=["pending", "held", "deferred"]),
                name="unique_active_retention_proposal",
            ),
        ]

    def __str__(self):
        return f"Löschvorschlag {self.target_type} ({self.get_status_display()})"


class LegalHold(models.Model):
    """Explicit postponement of deletion for a specific record."""

    objects = FacilityScopedManager()

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    facility = models.ForeignKey(
        "core.Facility",
        on_delete=models.CASCADE,
        related_name="legal_holds",
        verbose_name=_("Einrichtung"),
    )
    target_type = models.CharField(max_length=100, verbose_name=_("Zieltyp"))
    target_id = models.UUIDField(verbose_name=_("Ziel-ID"))
    reason = models.TextField(verbose_name=_("Begründung"))
    expires_at = models.DateField(
        null=True,
        blank=True,
        verbose_name=_("Ablaufdatum"),
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="legal_holds",
        verbose_name=_("Erstellt von"),
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("Erstellt am"))
    dismissed_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("Aufgehoben am"),
    )
    dismissed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="dismissed_holds",
        verbose_name=_("Aufgehoben von"),
    )

    @property
    def is_active(self):
        """A hold is active if not dismissed and not expired."""
        if self.dismissed_at:
            return False
        if self.expires_at and self.expires_at < date.today():
            return False
        return True

    class Meta:
        verbose_name = _("Legal Hold")
        verbose_name_plural = _("Legal Holds")
        ordering = ["-created_at"]

    def __str__(self):
        status = _("aktiv") if self.is_active else _("inaktiv")
        return f"Legal Hold {self.target_type} ({status})"
